- 작성자: [충남대학교 인공지능학과 장경선](http://www.cnu.ac.kr/~sun)

##기본 데이터 유형의 검사

In [ ]:
is.logical(T)
is.logical(F)

print(10 > 11)
is.logical(10 > 11)

is.numeric(1.4)

is.character("1.2")
is.character('1.2')

v <- c(1,2,3)
print(v)
is.character(v)
is.numeric(v)



[1] TRUE

[1] TRUE

[1] FALSE


[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] 1 2 3


[1] FALSE

[1] TRUE

In [ ]:
w <- c('a','b','c')
print(w)
is.vector(w)
is.character(w)

x <- c(T, F, T, F)
print(x)
is.vector(x)
is.character(x)
is.logical(x)

print('----')
is.integer(1L)
is.numeric(1L)
is.integer(1)
is.numeric(1)

[1] "a" "b" "c"


[1] TRUE

[1] TRUE

[1]  TRUE FALSE  TRUE FALSE


[1] TRUE

[1] FALSE

[1] TRUE

[1] "----"


[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

## vector, matrix, array
- 첨자는 0부터가 아니라 1부터 시작한다.
- 차원은 앞에서부터, a[first, seccond, third, ...]
- 백터는 1차원, 매트릭스는 2차원, 어레이는 3차원이상의 구조 
- 구성요소의 기본 데이터 유형은 동일해야 함. 

In [ ]:
v=c(1:10)
print(v)
m <- matrix(1:50, nrow=5)
print(m)
a <- array(1:200, dim<-c(5,10,2))
print(a)


 [1]  1  2  3  4  5  6  7  8  9 10
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    6   11   16   21   26   31   36   41    46
[2,]    2    7   12   17   22   27   32   37   42    47
[3,]    3    8   13   18   23   28   33   38   43    48
[4,]    4    9   14   19   24   29   34   39   44    49
[5,]    5   10   15   20   25   30   35   40   45    50
, , 1

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    6   11   16   21   26   31   36   41    46
[2,]    2    7   12   17   22   27   32   37   42    47
[3,]    3    8   13   18   23   28   33   38   43    48
[4,]    4    9   14   19   24   29   34   39   44    49
[5,]    5   10   15   20   25   30   35   40   45    50

, , 2

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]   51   56   61   66   71   76   81   86   91    96
[2,]   52   57   62   67   72   77   82   87   92    97
[3,]   53   58   63   68   73   78   83   88   93    98
[4,]   54   59   64   69   74   79   84   89   94    9

## 벡터 
- 1차원
- 인덱스외에 
- 이름으로도 접근 가능
- sc = c(50,60,70,30,70,90)
- names(sc) = c('math', 'music', 'art', 'lang', 'physics', 'chem')

In [ ]:
sc = c(50,60,70,30,70,90)
print(sc)
print('----')
names(sc) = c('math', 'music', 'art', 'lang', 'physics', 'chem')
print(sc)
print(sc['math'])
print(sc[1])

print(sc[1:3])

print(sc[c('math','art','chem')])

#print(sc['math':'chem']) # 오류가 생김 - 인덱스와 이름의 차이 
print(sc[c('math','chem','lang')])

[1] 50 60 70 30 70 90
[1] "----"
   math   music     art    lang physics    chem 
     50      60      70      30      70      90 
math 
  50 
math 
  50 
 math music   art 
   50    60    70 
math  art chem 
  50   70   90 
math chem lang 
  50   90   30 


## 벡터 - 이름과 값을 같이 주기
- v2 <- c(“a”=“alpha”, “b”=“beta”, “c”=“charlie“)
- v2 <- c(a=“alpha”, b=“beta”, c=“charlie“)
- 함수 str(v2) : 내부 구조(structure)를 자세히 보여줌. 


In [ ]:
v2 <- c(a="alpha", b="beta", c="charlie")
print(v2)
print(v2['a'])
print(v2[2])
str(v2)

v3 <- c("a"="alpha", "b"="beta", "c"="charlie")
print(v3)
print(v3['c'])
print(v3[2])
str(v3)

        a         b         c 
  "alpha"    "beta" "charlie" 
      a 
"alpha" 
     b 
"beta" 
 Named chr [1:3] "alpha" "beta" "charlie"
 - attr(*, "names")= chr [1:3] "a" "b" "c"
        a         b         c 
  "alpha"    "beta" "charlie" 
        c 
"charlie" 
     b 
"beta" 
 Named chr [1:3] "alpha" "beta" "charlie"
 - attr(*, "names")= chr [1:3] "a" "b" "c"


## 단독 원소는 벡터
- 인쇄된 모양으로 보면, 원소 한개와 원소 두개 차이가 없음.
- length(v) : 원소의 갯수 리턴

In [ ]:
my_apples <- 5
is.vector(my_apples)
print(my_apples)

my_oranges <- 'six'
is.vector(my_oranges)
print(my_oranges)
print(length(my_oranges))

my_orange2 <- c('six', 'seven')
is.vector(my_orange2)
print(my_orange2) # 인쇄된 모양으로 보면, 원소 한개와 원소 두개 차이가 없음. 
print(length(my_orange2))

[1] TRUE

[1] 5


[1] TRUE

[1] "six"
[1] 1


[1] TRUE

[1] "six"   "seven"
[1] 2


##벡터 내의 유형 자동 변환
- 벡터는 한 가지 기본 데이터 유형만 포함할 수 있음
- 유형 섞여 있으면 한가지 유형으로 자동 변환이 필요함. 
- class - 기본 유형 리턴

In [ ]:
ranks <- c(7, 4, "A", 10, "K", 3, "Q",2, "Q", F, T, TRUE, FALSE)
str(ranks)
print(ranks)
class(ranks)
is.character(ranks)
is.numeric(ranks)

 chr [1:13] "7" "4" "A" "10" "K" "3" "Q" "2" "Q" "FALSE" "TRUE" "TRUE" ...
 [1] "7"     "4"     "A"     "10"    "K"     "3"     "Q"     "2"     "Q"    
[10] "FALSE" "TRUE"  "TRUE"  "FALSE"


[1] "character"

[1] TRUE

[1] FALSE

## 벡터의 연산, 단일 상수와의 연산
- 단일 상수는 벡터와 같은 크기로 확장되어서 계산됨.
- 반복문을 사용한 것과 같은 효과가 발생함. 
- 벡터의 연산자에는 for() 반복문이 숨어 있음. 

In [ ]:
earn <- c(5, 10, 3)
print(earn)
earn1 <- earn * 34
print(earn1)
earn1 <- earn * c(34,34,34)
print(earn1)

#살제 계산은 반복문을 사용한 것과 같은 효과가 남.
earn2 <- earn
for(i in 1:length(earn2)) { earn2[i] <- earn2[i] * 34}
print(earn2)

[1]  5 10  3
[1] 170 340 102
[1] 170 340 102
[1] 170 340 102


In [ ]:
earn3 <- earn/3
print(earn3)

earn3 <- earn/c(3,3,3)
print(earn3)

#반복문 사용시.
earn4 <- earn
for(i in 1:length(earn4)) { earn4[i] <- earn4[i] / 3}
print(earn4)

[1] 1.666667 3.333333 1.000000
[1] 1.666667 3.333333 1.000000
[1] 1.666667 3.333333 1.000000


In [ ]:
earn5 = earn - 3
print(earn5)

earn6 = earn ^ 2 
print(earn6)


[1] 2 7 0
[1]  25 100   9


## 벡터 끼리의 연산에서도
- 많은 반복문을 연산자로 줄여서 사용할 수 있음. 

In [ ]:
# 많은 반복문을 연산자로 줄여서 사용할 수 있음. 
print( earn5 * earn6 / 2.5 + earn * earn2 - earn3 / earn4 * 3)

[1]  867 3677  303


## 벡터용 함수, 연산자들
- sum(), max(), min(), mean(), var(), 표준편차, 
- 많은 반복문이 포함되어 있음.
- 뎃셈, 최대값찾기, 최소값찾기, 평균값 찾기, 분산계산, 표준편차계산
- v > 0.5 : 크기 비교 (각 원소들과 0.5와 크기 비교) 

In [ ]:
v = runif(100)
print(v)
sum(v)
max(v)
min(v)
mean(v)
var(v)
sd(v)
print(v > 0.5)
print(v[v > 0.5])

  [1] 0.557947578 0.260022170 0.453766414 0.689022794 0.773141147 0.490000711
  [7] 0.940870501 0.545600825 0.791643858 0.037933370 0.495018139 0.306133480
 [13] 0.630741965 0.035563203 0.796109097 0.166728956 0.274111676 0.527035076
 [19] 0.542470053 0.122164306 0.040813435 0.767083914 0.397597214 0.104301624
 [25] 0.291837244 0.436266369 0.803736941 0.216252682 0.999548212 0.369797441
 [31] 0.013456647 0.063137772 0.062602816 0.347752973 0.667373450 0.511297956
 [37] 0.174086161 0.492624401 0.852451308 0.421601621 0.527300067 0.955544874
 [43] 0.162465495 0.505872004 0.043967123 0.670061270 0.403343815 0.950170161
 [49] 0.250674141 0.408868427 0.074154628 0.393425161 0.008231714 0.043723806
 [55] 0.520179703 0.553913618 0.809652968 0.856163986 0.501030456 0.002393717
 [61] 0.341692149 0.951121918 0.365076244 0.001444170 0.764162982 0.904968137
 [67] 0.624014672 0.268329287 0.726546516 0.356989634 0.937834899 0.355223675
 [73] 0.758224906 0.317256278 0.088831397 0.313685430 0.63320986

[1] 45.43864

[1] 0.9995482

[1] 0.00144417

[1] 0.4543864

[1] 0.07898175

[1] 0.2810369

  [1]  TRUE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE
 [13]  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE FALSE
 [25] FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE
 [37] FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [49] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
 [61] FALSE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [73]  TRUE FALSE FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE
 [85]  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE
 [97] FALSE  TRUE FALSE  TRUE
 [1] 0.5579476 0.6890228 0.7731411 0.9408705 0.5456008 0.7916439 0.6307420
 [8] 0.7961091 0.5270351 0.5424701 0.7670839 0.8037369 0.9995482 0.6673735
[15] 0.5112980 0.8524513 0.5273001 0.9555449 0.5058720 0.6700613 0.9501702
[22] 0.5201797 0.5539136 0.8096530 0.8561640 0.5010305 0.9511219 0.7641630
[29] 0.9049681 0.6240147 0.7265465 0.9378349 0

##벡터의 서브셋 취하기 
- 인덱스나 이름 사용
- v[1:5], v[c(1,3,6,9)]
- v[-2] : 2번 원소만 빼고 모두
- v[-c(1,2)] : 1,2번 원소만 뺴고 모두

In [ ]:
v <- c(a="alpha", b="beta", c="charlie", d="delta", e="echo")
v[1:3]
v[c(1,3,5)]
v[-2]
v[-c(1,2)]

a         b         c 
  "alpha"    "beta" "charlie"

a         c         e 
  "alpha" "charlie"    "echo"

a         c         d         e 
  "alpha" "charlie"   "delta"    "echo"

c         d         e 
"charlie"   "delta"    "echo"

## logical을 이용한 서브셋 취하기 - subset by logical vectors


In [ ]:
remain <- c(40,20,30,70,90, 15)
names(remain) <- c('a','b','c','d','e','f')
print(remain)
print(remain > 30)
print(remain > c(30,30,30,30,30,30) )

print(remain[remain>30])
print(remain[remain<30])
print(remain[remain>30 & remain<90])

print(remain[c(T,F)]) # # recycle c(T,F), 벡터가 반복됨!

 a  b  c  d  e  f 
40 20 30 70 90 15 
    a     b     c     d     e     f 
 TRUE FALSE FALSE  TRUE  TRUE FALSE 
    a     b     c     d     e     f 
 TRUE FALSE FALSE  TRUE  TRUE FALSE 
 a  d  e 
40 70 90 
 b  f 
20 15 
 a  d 
40 70 
 a  c  e 
40 30 90 


## matrix, array 다음에 ...


In [ ]:
m <- matrix(1:50, nrow=5)
print(m)
a <- array(1:200, dim<-c(5,10,2))
print(a)