- 작성자: [충남대학교 인공지능학과 장경선](http://www.cnu.ac.kr/~sun)

##vector

In [1]:
#vector
score1 = c(80,90,100,70,80)
names(score1) = c('kim','park','lee','shin','cho')
score1
score1['kim']
score1[1:2]


kim park  lee shin  cho 
  80   90  100   70   80

kim 
 80

kim park 
  80   90

##matrix

In [5]:
#matrix
score2 = matrix(sample(60:100,15),nrow=5,ncol=3)
colnames(score2) <- c('math','eng','lang')
rownames(score2) <-names(score1)
score2
score2['kim','math']
score2[1,2:3]

math eng lang
kim  92   88  68  
park 69   73  97  
lee  74   87  66  
shin 81   77  60  
cho  84   63  80

[1] 92

eng lang 
  88   68

##array

In [ ]:
 #array
score3 <- array(sample(60:100,45,replace=TRUE),dim=c(5,3,3),dimnames=list(rownames(score2),colnames(score2),c('expr','exam','team')) )
score3
print(score3)

, , expr

     math eng lang
kim    87  93   81
park   68  85   75
lee    87  63   70
shin   83  78   62
cho    89  90   93

, , exam

     math eng lang
kim    65  80   77
park   80  87   83
lee    84  97   67
shin   82  82   68
cho    78  80   85

, , team

     math eng lang
kim    60  73   65
park   80  63   78
lee    71  73   81
shin   96  77   66
cho    94  93   63

, , expr

     math eng lang
kim    87  93   81
park   68  85   75
lee    87  63   70
shin   83  78   62
cho    89  90   93

, , exam

     math eng lang
kim    65  80   77
park   80  87   83
lee    84  97   67
shin   82  82   68
cho    78  80   85

, , team

     math eng lang
kim    60  73   65
park   80  63   78
lee    71  73   81
shin   96  77   66
cho    94  93   63



## matrix 만들기

In [7]:
sc2 <- matrix( c(50,60,70,30,70,90), nrow=2, byrow=TRUE) # by default, column-major
print(sc2)

     [,1] [,2] [,3]
[1,]   50   60   70
[2,]   30   70   90


In [8]:
rownames(sc2) <- c('kim', 'lee')
colnames(sc2) <- c('math', 'art', 'lang')
print(sc2)
sc2

    math art lang
kim   50  60   70
lee   30  70   90


math art lang
kim 50   60  70  
lee 30   70  90

In [10]:
print(matrix(1:6, nrow=2)) # 기본은 열 먼저 채우기!!  행의 개수  정해주기 nrow=

print(matrix(1:6, ncol=3)) # 기본은 열 먼저 채우기!!   열의 개수 정해주기  ncol=

print(matrix(1:6, nrow=2, byrow=TRUE)) # 행 먼저 채우기 byrow=TRUE

print(matrix(2:3, nrow=2, ncol=3)) # 행과 열의 개수 설정, 개수가 모자라면 자동 반복
# recycle 1:3



     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
     [,1] [,2] [,3]
[1,]    2    2    2
[2,]    3    3    3


##rbind(), cbind() : row로 붙이기, column으로 붙이기

In [ ]:
print(cbind(1:3, 2:4))   # column 별로, 붙이기  cbind(  ) 

print(rbind(1:3, 5:7))  # row 별로,   붙이기  rbind(  )


     [,1] [,2]
[1,]    1    2
[2,]    2    3
[3,]    3    4
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    5    6    7


In [17]:
m <- matrix(1:6, byrow = TRUE, nrow = 2)
print(m)

print(rbind(m, 7:9)) # m의 마지막행에  행별 7:9를 붙임

print(cbind(m, c(10, 11))) # m의 마지막 열에  열별로  붙임


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
     [,1] [,2] [,3] [,4]
[1,]    1    2    3   10
[2,]    4    5    6   11


## rownames(), colnames()

In [ ]:
m <- matrix(1:6, nrow = 2, byrow=T) 
print(m)
rownames(m) <- c('r1','r2') #행 이름  지정
colnames(m) <- c('c1','c2','c3') #열 이름 지정
print(m)


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
   c1 c2 c3
r1  1  2  3
r2  4  5  6


In [ ]:
m <- matrix(1:6, nrow = 2, byrow=T, 
                   dimnames=list(c('r1','r2'), c('c1','c2','c3') ) ) 
print(m) 


   c1 c2 c3
r1  1  2  3
r2  4  5  6


## 자동유형변환 - 문자와 섞이면 모두 문자열로 변환

In [23]:
num <- matrix(1:8, ncol = 2)
num
class(num)
char <- matrix(LETTERS[1:6], nrow = 4, ncol = 3)
char
class(char)
numchar <- cbind(num, char)

class(numchar)
is.numeric(numchar)
# vector의 경우에도, character가 우선순위가 높음!
is.character(numchar)

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

[1] "matrix" "array"

[,1] [,2] [,3]
[1,] A    E    C   
[2,] B    F    D   
[3,] C    A    E   
[4,] D    B    F

[1] "matrix" "array"

[1] "matrix" "array"

[1] FALSE

[1] TRUE

## subset 취하기

In [ ]:
m <- matrix(sample(1:15,12),nrow=3)
print(m)

print(m[1,3])

print(m[1:2,2:3])

print(m[1,])

print(m[,2])

print(m[12])

print(m[8])

print(m[1,1:2])

     [,1] [,2] [,3] [,4]
[1,]    9   14    2   11
[2,]    3   15    5    7
[3,]    4   12    1    6
[1] 2
     [,1] [,2]
[1,]   14    2
[2,]   15    5
[1]  9 14  2 11
[1] 14 15 12
[1] 6
[1] 5
[1]  9 14


## subset with c()

In [28]:
m <- matrix(sample(1:15,12),nrow=3)
print(m)

print(m)
m
print(m[c(1,2),c(2,3)]) #1,3행의  2,4열  

print(m[c(2,3),c(4,1,2)]) #2,3행의  4,1,2열 



     [,1] [,2] [,3] [,4]
[1,]   15    1    7    4
[2,]   12    9   13    5
[3,]   14   10    8    2
     [,1] [,2] [,3] [,4]
[1,]   15    1    7    4
[2,]   12    9   13    5
[3,]   14   10    8    2


[,1] [,2] [,3] [,4]
[1,] 15    1    7   4   
[2,] 12    9   13   5   
[3,] 14   10    8   2

     [,1] [,2]
[1,]    1    7
[2,]    9   13
     [,1] [,2] [,3]
[1,]    5   12    9
[2,]    2   14   10


In [29]:
rownames(m)<- c('r1','r2','r3') 
colnames(m)<- c('c1','c2','c3','c4') 
print(m) 

print(m[2,3])

print(m['r1','c3']) #1행, 3열

print(m['r2',c('c2','c4')])#2행, 2,3열

print(m[c('r1','r3'),c('c2','c4')])#1,3행, 2,4열


   c1 c2 c3 c4
r1 15  1  7  4
r2 12  9 13  5
r3 14 10  8  2
[1] 13
[1] 7
c2 c4 
 9  5 
   c2 c4
r1  1  4
r3 10  2


## subset with logical

In [30]:
print(m)

m<=7        #7이하인 원소 위치가 TRUE인  matrix


m[m<=7]


m > 7       #7초과인 원소의 위치가 TRUE인 matrix

m[m>7]             # 매우  효과적인 원소  걸러내기


   c1 c2 c3 c4
r1 15  1  7  4
r2 12  9 13  5
r3 14 10  8  2


c1    c2    c3    c4  
r1 FALSE  TRUE  TRUE TRUE
r2 FALSE FALSE FALSE TRUE
r3 FALSE FALSE FALSE TRUE

[1] 1 7 4 5 2

c1   c2    c3    c4   
r1 TRUE FALSE FALSE FALSE
r2 TRUE  TRUE  TRUE FALSE
r3 TRUE  TRUE  TRUE FALSE

[1] 15 12 14  9 10 13  8

## matrix arithmetic

In [34]:
m

print('---')
m/2                    #모든 원소를 2로 나눈 matrix

print('---')
m2 <- matrix(2, nrow=dim(m)[1], ncol=dim(m)[2])
m2
m/m2

print('---')
m+1                   #모든 원소에 1을 더한 matrix

print('---')
m - m/2                 


c1 c2 c3 c4
r1 15  1  7 4 
r2 12  9 13 5 
r3 14 10  8 2

[1] "---"


c1  c2  c3  c4 
r1 7.5 0.5 3.5 2.0
r2 6.0 4.5 6.5 2.5
r3 7.0 5.0 4.0 1.0

[1] "---"


[,1] [,2] [,3] [,4]
[1,] 2    2    2    2   
[2,] 2    2    2    2   
[3,] 2    2    2    2

c1  c2  c3  c4 
r1 7.5 0.5 3.5 2.0
r2 6.0 4.5 6.5 2.5
r3 7.0 5.0 4.0 1.0

[1] "---"


c1 c2 c3 c4
r1 16  2  8 5 
r2 13 10 14 6 
r3 15 11  9 3

[1] "---"


c1  c2  c3  c4 
r1 7.5 0.5 3.5 2.0
r2 6.0 4.5 6.5 2.5
r3 7.0 5.0 4.0 1.0

## matrix - vector가 연산할때...

In [36]:
m

m - c(1,2,3)                   #c(1,2,3)이 열 중심으로 반복됨
m123 = matrix(c(1,2,3), nrow=dim(m)[1],ncol=dim(m)[2])

m123

m - m123

m - c(1,2,3,4)                #c(1,2,3)이 열 중심으로 반복됨


c1 c2 c3 c4
r1 15  1  7 4 
r2 12  9 13 5 
r3 14 10  8 2

c1 c2 c3 c4
r1 14 0   6  3
r2 10 7  11  3
r3 11 7   5 -1

[,1] [,2] [,3] [,4]
[1,] 1    1    1    1   
[2,] 2    2    2    2   
[3,] 3    3    3    3

c1 c2 c3 c4
r1 14 0   6  3
r2 10 7  11  3
r3 11 7   5 -1

c1 c2 c3 c4
r1 14 -3 4   2
r2 10  8 9   2
r3 11  8 7  -2

In [ ]:
print(dim(m))

m - matrix(c(1,2,3), nrow=dim(m)[1], ncol=dim(m)[2])


[1] 3 4


c1 c2 c3 c4
r1 8  13  1 10
r2 1  13  3  5
r3 1   9 -2  3

In [37]:
m = matrix(sample(1:15, 16, replace=T), nrow=4)
m

r = matrix(runif(16), nrow=4)
r

m*r


[,1] [,2] [,3] [,4]
[1,] 11    6    5    6  
[2,]  3    6    6   14  
[3,]  5    5    8   13  
[4,]  1   12   13   13

[,1]       [,2]      [,3]      [,4]     
[1,] 0.36744689 0.1539828 0.5262570 0.7378268
[2,] 0.36720999 0.8320689 0.6614923 0.4680525
[3,] 0.08158737 0.8993289 0.9259743 0.4519442
[4,] 0.82563317 0.6486512 0.1554005 0.8931895

[,1]      [,2]      [,3]     [,4]     
[1,] 4.0419158 0.9238966 2.631285  4.426961
[2,] 1.1016300 4.9924131 3.968954  6.552735
[3,] 0.4079369 4.4966445 7.407794  5.875275
[4,] 0.8256332 7.7838147 2.020207 11.611463

## colsums(), rowsums()

In [38]:
sc2 <- matrix( c(50,60,70,30,70,90), nrow=2, byrow=TRUE)
sc2

rownames(sc2) <- c('kim', 'lee')
colnames(sc2) <- c('math', 'art', 'lang')
sc2

rowSums(sc2)
rowSums(sc2)/dim(sc2)[2]  # 사람별 평균 점수

colSums(sc2)
colSums(sc2)/dim(sc2)[1]  # 과목별 평균 점수 

sum(sc2)/length(sc2)  #전체 평균


[,1] [,2] [,3]
[1,] 50   60   70  
[2,] 30   70   90

math art lang
kim 50   60  70  
lee 30   70  90

kim lee 
180 190

kim      lee 
60.00000 63.33333

math  art lang 
  80  130  160

math  art lang 
  40   65   80

[1] 61.66667

##array


In [ ]:
 #array
score3 <- array(sample(60:100,45,replace=TRUE),dim=c(5,3,3),dimnames=list(rownames(score2),colnames(score2),c('expr','exam','team')) )
score3
print(score3)

, , expr

     math eng lang
kim    74  79  100
park   98  60   73
lee    80  75   76
shin   90  65   71
cho    73  85   79

, , exam

     math eng lang
kim    90  60   65
park   86  72   73
lee    81  89   65
shin   83  84   88
cho    98  89   85

, , team

     math eng lang
kim    81  62   96
park   77  81   62
lee    77  72   88
shin   96  78   94
cho    84  79   69

, , expr

     math eng lang
kim    74  79  100
park   98  60   73
lee    80  75   76
shin   90  65   71
cho    73  85   79

, , exam

     math eng lang
kim    90  60   65
park   86  72   73
lee    81  89   65
shin   83  84   88
cho    98  89   85

, , team

     math eng lang
kim    81  62   96
park   77  81   62
lee    77  72   88
shin   96  78   94
cho    84  79   69



In [ ]:
sc3 <- array( seq(from=45,to=100,by=5), dim=c(2,3,2))
sc3
print(sc3)

, , 1

     [,1] [,2] [,3]
[1,]   45   55   65
[2,]   50   60   70

, , 2

     [,1] [,2] [,3]
[1,]   75   85   95
[2,]   80   90  100

In [ ]:
sc3 <- array( data=seq(from=45,to=100,by=5), dim=c(2,3,2), dimnames=list( c('kim', 'lee'), c('math', 'art', 'lang'), c('spring', 'fall') ) )
print(sc3)

, , spring

    math art lang
kim   45  55   65
lee   50  60   70

, , fall

    math art lang
kim   75  85   95
lee   80  90  100



##arithmetic

In [ ]:

print(sc3 * 3)

print('-------------')

print(sc3 ^ 2)

print('-------------')

print(sc3 - sc3)

, , spring

    math art lang
kim  135 165  195
lee  150 180  210

, , fall

    math art lang
kim  225 255  285
lee  240 270  300

[1] "-------------"
, , spring

    math  art lang
kim 2025 3025 4225
lee 2500 3600 4900

, , fall

    math  art  lang
kim 5625 7225  9025
lee 6400 8100 10000

[1] "-------------"
, , spring

    math art lang
kim    0   0    0
lee    0   0    0

, , fall

    math art lang
kim    0   0    0
lee    0   0    0



## subset

In [ ]:
print(sc3 > 50)

print(sc3[sc3 > 50])

, , spring

     math  art lang
kim FALSE TRUE TRUE
lee FALSE TRUE TRUE

, , fall

    math  art lang
kim TRUE TRUE TRUE
lee TRUE TRUE TRUE

 [1]  55  60  65  70  75  80  85  90  95 100


## dim(sc3), subset with index

In [ ]:
print(dim(sc3))

print(length(sc3))

print(sc3[1,,])

print(sc3[,2,])

print(sc3[,,1])

[1] 2 3 2
[1] 12
     spring fall
math     45   75
art      55   85
lang     65   95
    spring fall
kim     55   85
lee     60   90
    math art lang
kim   45  55   65
lee   50  60   70
